config/routes.rb
Rails.application.routes.draw do
  resources :presentations, only: [:index, :show]
  resources :curriculum, only: :index
  resources :case_studies, only: :index

  root 'curriculum#index'
end

app/models/curriculum.rb
class Curriculum
  def resume
    markdown_from_file("20150205.markdown")
  end

  def cover_letter
    markdown_from_file("cover-20150205.markdown")
  end

  def skills
    skills_file = File.join(this_directory, 'curriculums', 'skills.txt')
    File.readlines(skills_file)
  end

  def clients
    Curriculums::Client.all
  end

  def projects
    Curriculums::Project.all
  end

  def story
    markdown_from_file('story.md')
  end

  private

  def this_directory
   File.dirname(__FILE__)
  end

  def markdown_from_file(path)
    absolute_path = File.join(this_directory, 'curriculums', path)

    read_markdown(absolute_path)
  end

  def read_markdown(file_path)
    # load curriculm markdown
    cv_markdown = File.read file_path, mode: 'rt'
    markdown_processor = MyMarkdown.new cv_markdown

    # return html
    markdown_processor.content
  end
end

app/models/curriculums/client.rb
module Curriculums
  class Client
    attr_reader :url, :image
    def self.all
      clients_file = File.join(this_directory, "clients.txt")

      File.readlines(clients_file).map do |line|
        Client.new *line.split
      end
    end

    def initialize *args
      @url, @image = args
    end

    private

    def self.this_directory
      File.dirname(__FILE__)
    end
  end
end

app/models/curriculums/project.rb
module Curriculums
  class Project
    attr_reader :name, :url, :repo, :description
    def self.all
      projects_file = File.join(this_directory, "projects.txt")

      File.readlines(projects_file).map do |line|
        Project.new *line.split("|")
      end
    end

    def initialize *args
      @name, @url, @repo, @description = args
    end

    private

    def self.this_directory
      File.dirname(__FILE__)
    end
  end
end

app/models/my_markdown.rb
include ActionView::Helpers::AssetTagHelper
include ActionView::Helpers::UrlHelper

class MyMarkdown
  attr_reader :raw_content

  def initialize(raw_content, replacement_values = nil)
    @raw_content = raw_content
    @replacement_values = replacement_values

    markdown_renderer = Redcarpet::Render::HTML.new
    @markdown = Redcarpet::Markdown.new(markdown_renderer)
  end

  def content
    marked_content = @markdown.render(@raw_content)

    replace_tokens(marked_content)
  end

  private

  def replace_tokens(content)
    content.gsub(/(\[[^\[\]]*\])/) { |token| replace_photo_tokens(token[1..-2]) }
  end

  def replace_photo_tokens(title)
    article = @replacement_values[:article]
    photo = article.photos.find_by_title(title)

    return '' if photo.nil?

    <<-HTML
      <div id="item_#{photo.id}">
        <div class="thumbnail">
          #{image_tag(Photo.local_photos_dir + photo.thumbnail_fichier.filename, class: "photo-thumbnail")}
        </div>
      </div>
    HTML
  end
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  validates :unique_name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/case_studies_controller.rb
class CaseStudiesController < ApplicationController
  skip_before_action :authorize, only: [:index]

  def index
    @cv = Curriculum.new
  end
end

app/controllers/curriculum_controller.rb
class CurriculumController < ApplicationController
  skip_before_action :authorize, only: [:index]

  def index
    @cv = Curriculum.new
  end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: [:show]

  # GET /presentations
  # GET /presentations.json
  def index
    @presentations = Presentation.all
  end

  # GET /presentations/1
  # GET /presentations/1.json
  def show
    send_file "public/#{@presentation.filename}", type: 'application/pdf', disposition: 'inline'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.where(id: params[:id]).first || Presentation.where(unique_name: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presentation_params
      params.require(:presentation).permit(:name, :presented_at, :location, :filename)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/case_studies_helper.rb
module CaseStudiesHelper
end

app/helpers/curriculum_helper.rb
module CurriculumHelper
end

app/helpers/presentations_helper.rb
module PresentationsHelper
end

app/views/case_studies/index.html.slim
div class='container case-studies'
  h1 Case Studies

  div id="mywedhelper"
    div class='logo'
      img src="#{asset_path('mywedhelper.png')}"
    p
      | SaaS-based platform for brides to find the perfect vendor
    p
      | I am the creator of #{link_to('MyWedHelper.com', 'https:/www.mywedhelper.com')} a wedding platform for brides to find the perfect vendors.

    p
      b How did we do this:&nbsp;
      | First of all, I staged multiple conversations with the CEO for requirement-gathering.
    p
      b Immediate feedback:&nbsp;
      | A test server was deployed for a repaid feedback loop between the development team and the management team
    p
      b Integration:&nbsp;
      | We leveraged existing services such as Mandrill to communicate with our clients, and Strip to charge our clients (we also love our clients, so we frequently give them promotions).
    p
      b Code Quality:&nbsp;
      | Everything is well built. Why? Because our clients deserve to use the best platform. Their business is important to us.
    p
      b Technologies:&nbsp;
    div class='technologies'
      img src="#{asset_path('rails.png')}"
      img src="#{asset_path('ruby.png')}"
      img src="#{asset_path('html5.png')}"
      img src="#{asset_path('angular.svg')}"


  div id="showcare"
    img src="#{asset_path('showcare.png')}"
    p
      | SaaS provider for the conference industry. We built Libra, a magnificent web application that handled the logistics and management of many conferences all over the world. We had dozens of clients, each one bringing in thousands of users to the platform. And it worked well.

    p
      b Built It Right:&nbsp;
      | Technical decisions were based on concrete data. We used the fabulous #{link_to('MSDN', 'https://msdn.microsoft.com/en-ca/default.aspx')} and the #{link_to('.NET Reflector', 'http://www.red-gate.com/products/dotnet-development/reflector/')} tool as references.
    p
      b Technologies:&nbsp;
    div class='technologies'
      img src="#{asset_path('csharp.png')}"
      img src="#{asset_path('aspnet.png')}"
      img src="#{asset_path('sqlserver.png')}"

app/views/curriculum/index.html.slim
div class="jumbotron"
  div class="container"
    div class="row"
      div class="col-md-9"
        = raw @cv.cover_letter

      div class="col-md-3 contact"
        a id="email" href="mailto:dan.ofer@alumni.utoronto.ca" target='_blank'
          img src="#{asset_path('user-512px.svg')}"
          br
          p
            | dan.ofer@alumni.utoronto.ca
        a id="stack-overflow" href="https://careers.stackoverflow.com/ofer" target='_blank'
          img src="#{asset_path('stackoverflow.svg')}"
          br
          p
            | Stack Overflow
        a id="github" href="https://www.github.com/ofer987" target='_blank'
          img src="#{asset_path('github-circled-512px.svg')}"
          br
          p
            | GitHub

div class='container'
  a name='highlights'
  div class='projects'
    h2 Highlights
    div class='col-lg-4 left'
      img src="#{asset_path('mywedhelper.png')}"
      p
        | a SaaS-based platform for brides to find the perfect vendor
      ul
        li Ruby on Rails
        li Postgres
        li RESTful API JSON endpoints
        li Integration with Mandrill (email services) and Stripe (merchant services)
        li First service of its kind in Canada
      = link_to('Click here for Case Study', case_studies_url(anchor: 'mywedhelper'))

    div class='col-lg-4 right'
      img src="#{asset_path('showcare.png')}"
      p
        | a SaaS-based platform for complete management of major international conferences
      ul
        li ASP.NET
        li C#
        li SQL Server with Stored Procedures
        li Used by dozens of conference organizations every year
      = link_to('Click here for case study', case_studies_url(anchor: 'showcare'))

div class="container"
  a name="clients"
  div class="clients"
    h2 Clients
    - @cv.clients.each do |client|
      a class="client" href="#{client.url}" target="_blank"
        img src="#{asset_path(client.image)}"

div class="container"
  a name="projects"
  div class="projects"
    h2 Projects
    div class="row"
      - @cv.projects.each do |project|
        div class="col-lg-4"
          h3 #{project.name}
          p #{project.description}
          div class="btn-group" role="group"
            - unless project.url.blank?
              a class="project btn btn-primary" href="#{project.url}" target="_blank"
                | View
            - unless project.repo.blank?
              a class="project btn btn-info" href="#{project.repo}" target="_blank"
                | Repository

div class="container"
  div class="skills"
    a name="skills"
    h2 Skills
    div class="row"
      - @cv.skills.each do |skill|
        div class="col-lg-6"
          img src="#{asset_path('ok-512px.svg')}"
            span #{skill}

app/views/layouts/application.html.slim
doctype html
html
head
  title Dan Jakob Ofer
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

  javascript:
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-44599252-1', 'danofer.com');
    ga('send', 'pageview');

  /-- Google API --
  script src="https://maps.googleapis.com/maps/api/js?sensor=false"

body role="document"
  div class="page"
    div class="curriculum"
      nav class="navbar navbar-default navbar-fixed-top"
        div class="container"
          div class="navbar-header"
            = link_to('Dan Jakob Ofer', root_url, class: 'navbar-brand')
          div class="collapse navbar-collapse"
            ul class="nav navbar-nav"
              li
                = link_to('Case Studies', case_studies_url)
              li
                = link_to('Presentations', presentations_url)
      = yield

app/views/presentations/index.html.slim
div class='container'
  - @presentations.each do |presentation|
    = link_to "#{presentation.name} at #{presentation.location}", presentation
    br

app/views/presentations/show.html.slim
p#notice = notice

p
  strong Name:
  = @presentation.name
p
  strong Presented at:
  = @presentation.presented_at
p
  strong Location:
  = @presentation.location
p
  strong Filename:
  = @presentation.filename

= link_to 'Edit', edit_presentation_path(@presentation)
'|
= link_to 'Back', presentations_path